APP:
  HOST: http://localhost
  PORT: 8080
  JWT_SECRET: 0PKRQLVSdXyn9fa0vdB51B2pnHknYWGnwnOKAZve0umO46vVRWsWIn35GSvY
  EMAIL_ACCOUNT: arquitecturadeservidores@gmail.com
  EMAIL_PASSWORD: mzmmzmzzmzmmzmzzm1!
